### PR TITLE
Added ChiSquaredRV (r.f. PyMC3 PR #4695)

### PR DESCRIPTION
**Pull request by larryshamalama**
This PR adds a ChiSquaredRV class by addressing the ongoing refactoring of PyMC3 distributions [here](https://github.com/pymc-devs/pymc3/issues/4686). This PR is also a follow-up to [this](https://github.com/pymc-devs/pymc3/pull/4695) PR.

Still in the process of learning about the codebase, so please let me know if anything is wrong!

### CODE REVIEW

**Review by ricardoV94 — COMMENTED** [review]
If we rely on the numpy version we don't even need to specify the `call` and `rng_fn` methods as they will be automatically added. Just need to make sure the `name` attribute is called the same, I think (that is `chisquare` instead of `chi_squareD`. https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.chisquare.html#numpy.random.Generator.chisquare

**Review by ricardoV94 — COMMENTED** [review]
We also need some tests here: https://github.com/ricardoV94/aesara/blob/b02ef002a052226240088483baa9f1899f1479db/tests/tensor/random/test_basic.py

You can look at this for an straightforward example: https://github.com/ricardoV94/aesara/blob/b02ef002a052226240088483baa9f1899f1479db/tests/tensor/random/test_basic.py#L109

**Review by twiecki — APPROVED** [review]

**Comment by larryshamalama** [comment]
Corrected a typ<em>o</em>*

Corrected `ChiSquareRV` and added tests. Upon briefly [experimenting](https://github.com/larryshamalama/pymc3-playground/blob/master/aesara-pr414.ipynb), I'm still unsure if my tests are written correctly, but I follow closely `test_gamma_samples`.

**Comment by ricardoV94** [comment]
Ups I didn't squash and merge by accident :/

Thanks anyway @larryshamalama, that should be all on your part :D

**Pull request merged**
