### PR TITLE
Added Gumbel RV

### PR DESCRIPTION
**Pull request by fonnesbeck**
No tests yet.

Also added .vscode/ to .gitignore.

### CODE REVIEW

**Comment by brandonwillard** [comment]
Looks good!  It really should be as simple as that.

**Comment by fonnesbeck** [comment]
Cool, in that case I should be able to crank through a few of them. Do we want type hinting?

**Comment by brandonwillard** [comment]
> Do we want type hinting?

Always.

**Comment by ricardoV94** [comment]
Aren't we adding the new random variables on the PyMC3 side?

**Comment by brandonwillard** [comment]
> Aren't we adding the new random variables on the PyMC3 side?

Yes, but this one is an unimplemented `numpy.random` offering, so it should go here.

**Review by michaelosthege — CHANGES_REQUESTED** [review]
The RV looks good.

For the test I guess you can copyedit the one for the GammaRV?
https://github.com/pymc-devs/aesara/blob/master/tests/tensor/random/test_basic.py#L212-L217

**Comment by brandonwillard** [comment]
Ugh, looks like we need to fix JAX.

**Pull request merged**
