### PR TITLE
Added Laplace and Wald RV

### PR DESCRIPTION
**Pull request by kc611**
This PR adds a few of the missing RandomVariables required to build the new distributions in Pymc3.

### CODE REVIEW

**Comment by brandonwillard** [comment]
We might want to define these in PyMC3 (on the `v4` branch).  The rule-of-thumb is that we only include the `numpy.random` distributions in Aesara.

**Comment by kc611** [comment]
Alright, I guess that only `HalfNormal` uses `scipy.stats` so I'll remove that one from this PR.

What about `KumarswamyRV` it uses `rng` but the formulation is self defined. Should that one be relocated too?

**Comment by brandonwillard** [comment]
Yeah, I think `laplace` and `wald` are the only ones in `numpy.random`.

**Comment by brandonwillard** [comment]
We can use SciPy&mdash;or anything else&mdash;to generate the samples, it's just the NumPy API that we're trying to emulate.  It also helps us limit the size of Aesara, which could balloon if we attempted to cover all the distributions&mdash;like SciPy does.  

Plus, PyMC3 is definitely a more suitable place for work on distributions specifically.

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @kc611!

**Pull request merged**
