### PR TITLE
Add Numba conversions for shape and dimension manipulation `Op`s

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR adds Numba conversions for basic shape and dimension manipulation `Op`s.

### CODE REVIEW

**Comment by twiecki** [comment]
Great stuff!

**Review by michaelosthege — COMMENTED** [review]
The `numba_funcify_AllocEmpty*` functions could use a few comments and for `empty` and `full` docstrings and type hints would be great.
Other than that this looks technically fine to me.

**Comment by brandonwillard** [comment]
> The `numba_funcify_AllocEmpty*` functions could use a few comments and for `empty` and `full` docstrings and type hints would be great.
> Other than that this looks technically fine to me.

The PR isn't finished yet; for instance, there are still more tests to add.  Plus, I need to figure out how to log coverage in these cases, because Numba appears to not evaluate the actual `njit`ed functions.

**Comment by michaelosthege** [comment]
👍 


For coverage calculation you can do `export NUMBA_DISABLE_JIT=1` (see https://github.com/michaelosthege/pyrff/blob/master/.github/workflows/pipeline.yml#L33). IIRC this was the only way when I looked it up in May 2020.

**Comment by brandonwillard** [comment]
> For coverage calculation you can do `export NUMBA_DISABLE_JIT=1` (see https://github.com/michaelosthege/pyrff/blob/master/.github/workflows/pipeline.yml#L33). IIRC this was the only way when I looked it up in May 2020.

I'm aware.

**Pull request merged**
