### PR TITLE
Rename Aesara→pytensor

### PR DESCRIPTION
**Pull request by michaelosthege**
This PR renames the project as decided internally.

### Rename related changes
* Aesara → Pytensor
* aesara → pytensor
* AESARA → PYTENSOR
* Applied pre-commit
* GitHub repository URL
* Contact email addresses → pymc.devs@gmail.com

### Further changes
+ Upgraded mypy and fixed a platform-specific mypy error

### CODE REVIEW

**Comment by ricardoV94** [comment]
When should we change the aliases? `import pytensor.tensor as pt`

**Comment by michaelosthege** [comment]
> When should we change the aliases? `import pytensor.tensor as pt`

I would either not do it already (to keep pulling upstream easier) or do it in a follow-up PR.

Getting this rename merged early means that we can start splitting up tasks

**Review by ricardoV94 — APPROVED** [review]

**Comment by twiecki** [comment]
@michaelosthege Do you have the code you used for this?

**Comment by michaelosthege** [comment]
> 

`Ctrl+Shift+H` in VS Code, then search "Aesara" with case-sensitivity, replace by "PyTensor"...

I did this manually for the three bullet points in the description, then searched again for `pytensor-devs` and `pytensor.devs` to find the URLs and Email addresses and fixed those manually.

**Pull request merged**
