### PR TITLE
Replace C assertions with NAN in `gamma.c` and add tests for valid inputs

### LINKED ISSUE #224: Return NaN in C implementations of SciPy Ops
This is related to https://github.com/pymc-devs/pymc3/issues/4340

I am trying to use the `GammaIncc` Op, which makes use of the C code function `GammaQ`, which begins with an assertion for the two parameters. This is problematic when using the tensor version of the scalar op (via @_scal_elemwise), as I don't see how to gracefully avoid the assertion error.

To make this concrete, gammaincc is being used in the logcdf method of the pymc3 InverseGamma distribution. It is wrapped inside a `bound` which seems to lazy evaluate when working with scalars, but not with tensors. This allows it to gracefully return -np.inf when evaluated with invalid scalar arguments, but not when using a tensor/array.

The `scipy.special.gammaincc(x, k)` counterpart does not have this issue.

Does anyone know a workaround to avoid this issue when working with tensors?

```python
pm.InverseGamma.dist(alpha=-1, beta=5).logcdf(1).eval()  # returns -np.inf
pm.InverseGamma.dist(alpha=-1, beta=5).logcdf(np.array([1])).eval()  # fails assertion and exits process
```

```python
python3: /home/ricardo/.theano/compiledir_Linux-5.4--generic-x86_64-with-glibc2.29-x86_64-3.8.5-64/tmpf82kd0bh/mod.cpp:240: double GammaQ(double, double): Assertion `(n > 0) && (x >= 0)' failed.
Aborted (core dumped)

```

https://github.com/pymc-devs/pymc3/blob/043129243436b875a9ab18180549491c4678b7c6/pymc3/distributions/continuous.py#L2654-L2659

```python
return bound(
    tt.log(tt.gammaincc(alpha, beta / value)),
    value >= 0,
    alpha > 0,
    beta > 0,
)
```

https://github.com/pymc-devs/Theano-PyMC/blob/2601e7acf8442422cab19db5bd029a5581f0bdec/theano/tensor/basic.py#L2529-L2531

https://github.com/pymc-devs/Theano-PyMC/blob/819122e66bcd089b2a3f472542800feead0bf755/theano/scalar/basic_scipy.py#L598-L639

https://github.com/pymc-devs/Theano-PyMC/blob/819122e66bcd089b2a3f472542800feead0bf755/theano/scalar/c_code/gamma.c#L227-L233

### PR DESCRIPTION
**Pull request by ricardoV94**
Closes #224 

I am not sure if it's as simple as this... Still researching a bit. I haven't found a single C example that explicitly returns NAN, so I might be doing something wrong. The code works on my machine though.

***

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.  If your commit description starts with "Fix...", then you're probably making this mistake.
+ [x] There are tests covering the changes introduced in the PR.

### CODE REVIEW

**Review by brandonwillard — CHANGES_REQUESTED** [review]
Yeah, I think that's all there is to it, but the use of `NAN` might need some attention.  

I don't know if `NAN` is universally offered &mdash;and/or always works the way it needs to.  Take a look at the code generated by Cython; I believe it creates a macro for a stable `NAN`.

**Comment by ricardoV94** [comment]
My understanding is that the isoc99 guarantees the macro for Nan in math.c, but I will double check

**Comment by ricardoV94** [comment]
I did some research and I am still pretty unsure where we can rely on the `math.h` NAN macro...

One alternative could be to use NPY_NAN by including `npy_math.h`:
https://github.com/numpy/numpy/blob/e80b1935d81b8ea36e43f7f5ac63629b6dd756f9/numpy/core/include/numpy/npy_math.h#L60

This is what Scipy does with its gamma functions in `igam.c`: 
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/special/cephes/igam.c#L134

Via `mconf.h`: https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/special/cephes/mconf.h#L57

**Comment by ricardoV94** [comment]
And I guess this is what you had in mind with how Cython defines NAN?

https://github.com/cython/cython/blob/b738fd8c0f19c2fdd510f1a0c1a581509f6e836f/Cython/Utility/ModuleSetupCode.c#L1112-L1123

**Comment by brandonwillard** [comment]
> And I guess this is what you had in mind with how Cython defines NAN?
> 
> https://github.com/cython/cython/blob/b738fd8c0f19c2fdd510f1a0c1a581509f6e836f/Cython/Utility/ModuleSetupCode.c#L1112-L1123

Exactly

**Comment by ricardoV94** [comment]
Personally, I would be more comfortable just relying on the Numpy NAN macro, than implementing it again: https://numpy.org/doc/stable/reference/c-api/coremath.html

Do you see a problem with this?

**Comment by brandonwillard** [comment]
> Do you see a problem with this?

Not if the required libraries are already being linked.

**Comment by ricardoV94** [comment]
Do we need to do anything else?

**Comment by brandonwillard** [comment]
Looks like we need to change the CI change detection so that it recognizes C source files (e.g. `.c` and `.h` extensions, at least), because it looks like the tests were skipped.

**Review by brandonwillard — CHANGES_REQUESTED** [review]
OK, now the most important part: tests.

**Comment by ricardoV94** [comment]
It seems like the gamma functions are not being tested anywhere at all. Do you have any suggestion as to what is the appropriate scope here? Just testing for NAN seems... dangerous. Should we have a more comprehensive matches scipy kind of test?

**Comment by dfm** [comment]
It's been a long standing issue that the C implementation of the gamma functions are never tested. This resulted in at least one longstanding bug: https://github.com/Theano/Theano/pull/6751 I still don't understand why this is!

**Comment by brandonwillard** [comment]
There are tests for the entire `aesara.scalar.basic_scipy` module in `tests.tensor.test_basic_scipy`.  The reason they aren't in `tests.scalar` is that they're all set up as "broadcast" tests (i.e. `Elemwise` tests).  They really shouldn't be `Elemwise` tests, because `Elemwise` is already well tested in those ways and the extra effort is effectively wasted, so that's a change we need to make down the line.

The next problem is the exact implementation being tested by those existing `Elemwise` tests (e.g. the C or Python implementation).  That's where we start to see lots of problems with the old/current test suite: it uses compilation modes that include and depend on too many other things.  In this case, though, I do believe that the test will compile to C.  Unfortunately, that would imply that the Python (i.e. `Op.perform`) methods aren't being tested.

What we need are tests that provide coverage for _both_ the C and Python code explicitly.  To do that, one only needs to call `function` with a hand-made `Mode` that specifies **no** optimizations and either the `PerformLinker` or `CLinker`&mdash;depending on which one you're testing at the time.  Better yet, one can skip the mode settings entirely and simply use a `FunctionGraph` and the linkers directly: e.g. `PerformLinker().accept(FunctionGraph(inputs, outputs)).make_function()`.

Anyway, good tests would use both linkers and provide coverage for **only our code**.  

For the `Op`s in `aesara.scalar.basic_scipy`, the `PerformLinker` needs only a single evaluation in most cases, because the underlying `Op.perform` goes straight to SciPy (and we're not in the business of testing SciPy's code).  

The `CLinker` tests need more attention, because we've implemented a few of those by hand, and, just like Python testing, we need to write tests with inputs that go through all the conditions in `aesara/scalar/c_code/gamma.c`&mdash;at the very least.

The above two tests are for `Op.perform` and `Op.c_code`.  After those are tested, we need tests for `Op.L_op` (i.e. the gradient implementations), when present.  The easy way to do that is with `tests.unittest_tools.verify_grad` and some carefully chosen inputs.

Since you've only changed a small part of the C code, you can just create a new `tests.scalar.test_basic_scipy` module and use the `CLinker` approach with the appropriate inputs and `np.isnan` `assert`s.

**Comment by ricardoV94** [comment]
> There are tests for the entire `aesara.scalar.basic_scipy` module in `tests.tensor.test_basic_scipy`.

I find only tests for gamma, gammaln, and tri_gamma. I don't see any tests for gammainc, gammaincc, gammau, and gammal. Indeed in the PR were these were added, no tests seem to have been included: https://github.com/Theano/Theano/pull/6648/files

**Comment by ricardoV94** [comment]
So the question is: Should I add the previously missing tests to `tests.tensor.test_basic_scipy` (even though we don't like this approach, I think it will be easier to refactor later on if everything is consistent up to that point), and separately add some `nan` tests in `tests.scalar.test_basic_scipy` to address the specific changes introduced in this PR?

**Comment by ricardoV94** [comment]
Noob question, I am trying to implement the nans test with the `Clinker` approach that you suggested, but it's not quite working for me:

```python
import aesara.tensor as aet
from aesara.scalar.basic_scipy import gammainc, gammaincc, gammau, gammal
from aesara.graph.fg import FunctionGraph
from aesara.link.c.basic import CLinker

x1 = aet.dscalar('x')
x2 = aet.dscalar('y')
y = gammaincc(x1, x2)
test_func = CLinker().accept(FunctionGraph([x1, x2], y)).make_function()
print(test_func(-1, 1))
```
```python
Traceback (most recent call last):
  File "/home/ricardo/Documents/Projects/Theano-PyMC/tests/scalar/test_basic_scipy.py", line 10, in <module>
    test_func = CLinker().accept(FunctionGraph([x1, x2], y)).make_function()
  File "/home/ricardo/Documents/Projects/Theano-PyMC/aesara/graph/fg.py", line 115, in __init__
    inputs, outputs = clone_graph(inputs, outputs)
  File "/home/ricardo/Documents/Projects/Theano-PyMC/aesara/graph/basic.py", line 900, in clone
    equiv = clone_get_equiv(inputs, outputs, copy_inputs, copy_orphans)
  File "/home/ricardo/Documents/Projects/Theano-PyMC/aesara/graph/basic.py", line 950, in clone_get_equiv
    for apply in io_toposort(inputs, outputs):
  File "/home/ricardo/Documents/Projects/Theano-PyMC/aesara/graph/basic.py", line 1156, in io_toposort
    todo = [o.owner for o in reversed(outputs) if o.owner]
TypeError: 'ScalarVariable' object is not reversible
```

**Comment by ricardoV94** [comment]
Good news is that the new broadcast tests are failing because the nans are working :b

**Comment by ricardoV94** [comment]
Seemingly unrelated  test failure: `FAILED tests/compile/test_compilelock.py::test_locking_thread - assert True i...`

**Comment by brandonwillard** [comment]
> Seemingly unrelated test failure: `FAILED tests/compile/test_compilelock.py::test_locking_thread - assert True i...`

I don't see this failure.

> And `FAILED tests/tensor/test_math.py::TestModBroadcast::test_grad - aesara.gradie...`

Depending on the exact nature of this error, it's possible that the newly added tests changed the poorly designed RNG seeding in the test suite.  In other words, some tests are implicitly dependent on the exact seed value, which is affected by the order in which the tests are run, so keep an eye out for that.

**Comment by brandonwillard** [comment]
> Noob question: I am trying to implement the nans test with the `Clinker` approach that you suggested, but it's not quite working for me. What am I doing wrong?
> 
> ```python
> import aesara.tensor as aet
> from aesara.scalar.basic_scipy import gammainc, gammaincc, gammau, gammal
> from aesara.graph.fg import FunctionGraph
> from aesara.link.c.basic import CLinker
> 
> x1 = aet.dscalar('x')
> x2 = aet.dscalar('y')
> y = gammainc(x1, x2)
> test_func = CLinker().accept(FunctionGraph([x1, x2], y)).make_function()
> print(test_func(-1, 1))
> ```

Look like you're not calling `FunctionGraph` correctly; _both_ arguments should be lists.

**Comment by ricardoV94** [comment]
> > Seemingly unrelated test failure: `FAILED tests/compile/test_compilelock.py::test_locking_thread - assert True i...`
> 
> I don't see this failure.

I can't find it either... I guess it will resurface again if I did not imagine it

**Comment by ricardoV94** [comment]
> > And `FAILED tests/tensor/test_math.py::TestModBroadcast::test_grad - aesara.gradie...`
> 
> Depending on the exact nature of this error, it's possible that the newly added tests changed the poorly designed RNG seeding in the test suite. In other words, some tests are implicitly dependent on the exact seed value, which is affected by the order in which the tests are run, so keep an eye out for that.

Failed again. I can reproduce locally:
```python
_grad_broadcast_div_mod_normal = dict(
    # same_shapes=(rand(2, 3), rand_nonzero((2, 3))),
    same_shapes=(
        np.array([[0.16248044, -0.98288917, -0.33407401], [0.35973542,  0.11859988,  0.58337884]]),
        np.array([[0.85552586, -0.00677909, -0.12264811], [-0.21154757,  0.23006721,  0.3854657]])
    ),
    scalar=(rand(2, 3), rand_nonzero((1, 1))),
    row=(rand(2, 3), rand_nonzero((1, 3))),
    column=(rand(2, 3), rand_nonzero((2, 1))),
)

TestModBroadcast = makeBroadcastTester(
    op=mod,
    expected=lambda x, y: np.asarray(x % y, dtype=aes.upcast(x.dtype, y.dtype)),
    good=copymod(_good_broadcast_div_mod_normal_float, ["complex1", "complex2"]),
    grad=_grad_broadcast_div_mod_normal,
    grad_eps=1e-5,
)
```
I don't think this is an issue with the seed in `unittest_tools::verify_grad` (I changed it a couple of times locally). So it has to do with the random `_grad_broadcast_div_mod_normal` input. Is this a bug, or is it reasonable for the finite difference method and theano grad to differ with this input, by this much?

**Comment by brandonwillard** [comment]
> I get ~1/10 failing cases for randomly generated `same_shapes` values.

If that's the case, and your code changes had literally nothing to do with this `mod` `Op`&mdash;aside from inadvertently shifting the RNG state used by this test&mdash;then my advice _is_ applicable here.

Here's a good thing to check: do you observe a similar failure rate when changing the seed in `master` (or the original Theano)?  More importantly, do you see similar error magnitudes for the same inputs?

If this problem is entirely due to the RNG state, and those numeric errors aren't caused by underlying implementation errors in the `mod` `Op`, then the errors you're seeing might be in line with a discrepancy between a finite-difference approximation vs. an analytic derivative.  That wouldn't be too surprising given the discrete nature of the `Op` in question and its derivative.

**Comment by ricardoV94** [comment]
I confirmed that it fails (also in master) whenever the modulo is close to zero.

This fails 7/100 times.
```python
@pytest.mark.parametrize('n', range(100))
def test_failure_rate(n):
    _grad_broadcast_div_mod_normal = dict(
        same_shapes=(rand(2, 3), rand_nonzero((2, 3))),
        scalar=(rand(2, 3), rand_nonzero((1, 1))),
        row=(rand(2, 3), rand_nonzero((1, 3))),
        column=(rand(2, 3), rand_nonzero((2, 1))),
    )
    for testname, inputs in _grad_broadcast_div_mod_normal.items():
        inputs = [copy(input) for input in inputs]
        utt.verify_grad(
            mod,
            inputs,
            mode=None,
            rel_tol=None,
            eps=1e-5,
        )
```

If I increase the default eps things work much better.
This fails 2/1000 times :
```python
@pytest.mark.parametrize('n', range(1000))
def test_failure_rate(n):
    _grad_broadcast_div_mod_normal = dict(
        same_shapes=(rand(2, 3), rand_nonzero((2, 3))),
        scalar=(rand(2, 3), rand_nonzero((1, 1))),
        row=(rand(2, 3), rand_nonzero((1, 3))),
        column=(rand(2, 3), rand_nonzero((2, 1))),
    )
    for testname, inputs in _grad_broadcast_div_mod_normal.items():
        inputs = [copy(input) for input in inputs]
        utt.verify_grad(
            mod,
            inputs,
            mode=None,
            rel_tol=None,
            eps=1e-7,
        )
```

**Comment by ricardoV94** [comment]
Silly me, I forgot to check if the original failing inputs passed with the new eps_grad... They do not. I'll be back

**Comment by ricardoV94** [comment]
It did work locally, on 64bit, but it still fails on 32 bit. Any tips on how to reseed this one?

**Comment by brandonwillard** [comment]
> Any tips on how to (cleanly) reseed this one?

This doesn't appear to be about seeding; the problem is in the approach.  As with all of these tests, we actually need to use well chosen inputs that explicitly test each part of our implementations.  

There's simply no reason to randomly test portions of the code; these functions/methods we're testing aren't complex enough to justify the approach.  Plus, fixing a seed forfeits whatever benefit we would get from sampling&mdash;besides the time saved by not writing good tests.

Looking at `aesara.scalar.basic.Mod.c_code`, we can see a few conditions that tell us which points need to be present: a [integer and float point](https://github.com/pymc-devs/aesara/blob/fix-local-grad-log-erfc-neg/aesara/scalar/basic.py#L2147), [`y == 0`](https://github.com/pymc-devs/aesara/blob/fix-local-grad-log-erfc-neg/aesara/scalar/basic.py#L2196), [`y < 0` and `x < 0`](https://github.com/pymc-devs/aesara/blob/fix-local-grad-log-erfc-neg/aesara/scalar/basic.py#L2198), etc.  Unlike many of the current tests, we **don't** need to test _every_ combination of `dtype` and value; in most cases, that approach only wastes time repeating the same branches.

I'm not even sure that we need to do these comparisons with the numerical derivative/gradient (in most cases, as well).  It only makes sense when we're not sure that we've implemented the correct analytic derivative, and that's a rather different problem that should be addressed separately and directly.

My guess is that the points previously used to test `Mod` were nowhere near equal, nor did `x` divide `y`, so the derivatives would all evaluate to zero.  Again, tests like that are mostly a waste of time.  Instead, we can pick a few good points to test and just make sure that the implementation is computing the known derivative.

**Comment by ricardoV94** [comment]
> Looking at `aesara.scalar.basic.Mod.c_code`, we can see a few conditions that tell us which points need to be present: a [integer and float point](https://github.com/pymc-devs/aesara/blob/fix-local-grad-log-erfc-neg/aesara/scalar/basic.py#L2147), [`y == 0`](https://github.com/pymc-devs/aesara/blob/fix-local-grad-log-erfc-neg/aesara/scalar/basic.py#L2196), [`y < 0` and `x < 0`](https://github.com/pymc-devs/aesara/blob/fix-local-grad-log-erfc-neg/aesara/scalar/basic.py#L2198), etc. 

Those are being tested in the `good` branch of the `makeBroadcastTester` and they work fine since it's deterministic value is simply compared to the numpy / scipy one.

> My guess is that the points previously used to test Mod were nowhere near equal, nor did x divide y, so the derivatives would all evaluate to zero. Again, tests like that are mostly a waste of time. Instead, we can pick a few good points to test and just make sure that the implementation is computing the known derivative.

The issue is indeed whether `x` and `y` are too similar. The derivative for floats `x`, `y` is not zero (at least the L_op, which I assume appears in the grad tests, is not): https://github.com/pymc-devs/aesara/blob/02a0c59d5053dddef84102ffaff3f31ef4a2cfd2/aesara/scalar/basic.py#L2214-L2223

Anyway, I fixed the random values, making sure all `x` and `y` are distinct enough and I added a comment explaining this decision.

**Pull request merged**
